yosimitso_working_forum:
    thread_per_page: 20
    post_per_page: 10
    date_format: 'Y/m/d H:i'
    allow_anonymous_read: true
    allow_moderator_delete_thread: true
    theme_color: green
    lock_thread_older_than: 365
    post_flood_sec: 30
    site_title: "My Website"
    vote:
        threshold_useful_post: 5
    file_upload:
        enable: true
        max_size_ko: 5000
        accepted_format: [image/jpg, image/jpeg, image/png, image/gif, image/tiff, application/pdf]
        preview_file: true
    thread_subscription:
        enable: true
